version: '3.5'

services:
  db:  # postgres database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=example_db_user  # choose a database username
      - POSTGRES_PASSWORD=rEaLlYbaDPa$sw0rD  # choose a database password
      - POSTGRES_DB=ssm  # choose a database name
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data/  # assumes non-transient host directory at $build_directory/postgres/postgres_data
  adminier:  # optional database admin app
    image: adminer:latest
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
    - db
  app:
    image: aninstance/simple-stock_management
    restart: always
    environment:
      - DEBUG=1
      - APP_URL=localhost
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=ssm  # match postgres database name (chosen above)
      - SQL_USER=example_db_user  # match postgres username (chosen above)
      - SQL_PASSWORD=rEaLlYbaDPa$sw0rD  # match postgres password (chosen above)
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres  # comment out to use sqlite (transient - will be destroyed with container!)
    volumes:
      - ./config:/config
      - ./config/secret_key:/src/secret_key
      - ./log:/var/log # assumes non-transient host directory at $build_directory/log
      - ./static:/src/static # assumes non-transient host directory at $build_directory/static
      - ./media:/src/media  # assumes non-transient host directory at $build_directory/media
      - ./config/settings.docker.py:/src/StockManagement/settings.py # assumes settings.docker.py file (edit to spec) at $build_directory/config/settings.docker.py
    entrypoint: /config/entrypoint.sh
    expose:
      - 8000
    depends_on:
    - db
  nginx:
    image: aninstance/simple-stock-management-client
    restart: always
    volumes:
      - ./static:/var/www/html/static  # assumes non-transient host directory at $build_directory/static
      - ./media:/var/www/html/media  # assumes non-transient host directory at $build_directory/media
      - ./log:/var/log/nginx  # assumes non-transient host directory at $build_directory/log/nginx
      - ./config/nginx/ssm.conf:/etc/nginx/conf.d/ssm.conf.new  # assumes spm.conf (edit to spec) at $build_directory/config/nginx/spm.conf
      - ./config/.env.docker:/npm_build/.env.docker.new # assumes .env.docker file (edit to spec) at $build_directory/config/.env.docker
    ports:
      - 127.0.0.1:1337:80  # makes app available at http://localhost:1337. Change to 127.0.0.1:1337:443 if connecting over TLS with secure settings.py
    depends_on:
      - app
    entrypoint: /nginx-entrypoint.sh